-- GreatSQL AP测试脚本
-- 用于测试Turbo、Rapid引擎
-- 先测试Turbo引擎，后测试Rapid引擎

SELECT '--- SELECT VERSION() ---';
SELECT @@version, @@version_comment;

SELECT '--- CREATE DB greatsql, GREATE TABLE t1, INSERT SOME ROWS, SELECT ROWS ---';
SELECT 'CREATE DATABASE IF NOT EXISTS greatsql;' AS EXEC_TEST_SQL;
CREATE DATABASE IF NOT EXISTS greatsql;
SELECT 'USE greatsql;' AS EXEC_TEST_SQL;
USE greatsql;

SELECT 'DROP TABLE IF EXISTS t1;' AS EXEC_TEST_SQL;
DROP TABLE IF EXISTS t1;

SELECT '
CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 VARCHAR2(30) NOT NULL DEFAULT \'\', 
c2 INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;' AS EXEC_TEST_SQL;
CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 VARCHAR2(30) NOT NULL DEFAULT '',
c2 INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'SHOW CREATE TABLE t1\G' AS EXEC_TEST_SQL;
SHOW CREATE TABLE t1\G

SELECT 'INSERT INTO t1 VALUES 
(0, rand(), ROUND(RAND()*1024000)) ... ' AS EXEC_TEST_SQL;
INSERT INTO t1 VALUES 
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000));

INSTALL PLUGIN turbo SONAME 'turbo.so';

SELECT 'EXPLAIN FORMAT=TREE SELECT /*+SET_VAR(turbo_enable=ON) SET_VAR(turbo_cost_threshold=0)*/ * FROM t1 WHERE id >= 1;' AS EXEC_TEST_SQL;
EXPLAIN FORMAT=TREE SELECT /*+SET_VAR(turbo_enable=ON) SET_VAR(turbo_cost_threshold=0)*/ * FROM t1 WHERE id >= 1;

SELECT 'UNINSTALL PLUGIN turbo;' AS EXEC_TEST_SQL;
UNINSTALL PLUGIN turbo;

SELECT 'INSTALL PLUGIN rapid SONAME "ha_rapid.so";' AS EXEC_TEST_SQL;
INSTALL PLUGIN rapid SONAME 'ha_rapid.so';

SELECT 'ALTER TABLE t1 SECONDARY_ENGINE = rapid;' AS EXEC_TEST_SQL;
ALTER TABLE t1 SECONDARY_ENGINE = rapid;

SELECT 'SHOW CREATE TABLE t1\G' AS EXEC_TEST_SQL;
SHOW CREATE TABLE t1\G

SELECT 'ALTER TABLE t1 SECONDARY_LOAD;' AS EXEC_TEST_SQL;
ALTER TABLE t1 SECONDARY_LOAD;

SELECT "SHOW TABLE STATUS LIKE 't1'\G" AS EXEC_TEST_SQL;
SHOW TABLE STATUS LIKE 't1'\G

SELECT 'EXPLAIN SELECT /*+SET_VAR(use_secondary_engine=1) SET_VAR(secondary_engine_cost_threshold=0)*/ * FROM t1 WHERE id >= 1;' AS EXEC_TEST_SQL;
EXPLAIN SELECT /*+SET_VAR(use_secondary_engine=1) SET_VAR(secondary_engine_cost_threshold=0)*/ * FROM t1 WHERE id >= 1;

SELECT 'ALTER TABLE t1 SECONDARY_ENGINE = null;' AS EXEC_TEST_SQL;
ALTER TABLE t1 SECONDARY_ENGINE = null;

SELECT 'UNINSTALL PLUGIN rapid;' AS EXEC_TEST_SQL;
UNINSTALL PLUGIN rapid;
